
const $ = s => document.querySelector(s);
const $$ = s => [...document.querySelectorAll(s)];

const pageMeta = {
  projects:["Projects","Create a new workpiece or reopen an existing project."],
  chat:["Forge Chat","Talk normally. ForgeBoss remembers the project and promotes only authoritative decisions."],
  forge:["Forge","See exactly what ForgeBoss is doing, how far it has progressed, and how much fuel it has used."],
  bible:["Bible","The authoritative project foundation ForgeBoss builds and works from."],
  evidence:["Evidence","Tests, hostile review and proof generated by the forge."],
  vault:["Forge Vault","AI providers, Git connections and protected credentials."],
  settings:["Settings","Default forge time, fuel caps, modes and memory behaviour."]
};

function showPage(id){
  $$(".page").forEach(p=>p.classList.toggle("active",p.id===id));
  $$(".nav").forEach(n=>n.classList.toggle("active",n.dataset.page===id));
  $("#pageTitle").textContent=pageMeta[id][0];
  $("#pageSub").textContent=pageMeta[id][1];
}
$$(".nav").forEach(n=>n.onclick=()=>showPage(n.dataset.page));

$$(".tab").forEach(t=>t.onclick=()=>{
  $$(".tab").forEach(x=>x.classList.toggle("active",x===t));
  $$(".source").forEach(x=>x.classList.toggle("active",x.id==="src-"+t.dataset.source));
});

let currentProject = localStorage.getItem("fb_project") || "";
let chats = JSON.parse(localStorage.getItem("fb_chats") || "[]");
let logs = [
  ["17:05","● Tempering with acceptance tests"],
  ["17:04","✓ Changes stayed inside approved scope"],
  ["17:03","✓ Repair Rat shaped the candidate repair"]
];

function setProject(name){
  currentProject=name;
  localStorage.setItem("fb_project",name);
  $("#activeProjectChip").textContent=name||"No project loaded";
  renderRecents();
}
if(currentProject) $("#activeProjectChip").textContent=currentProject;

function renderRecents(){
  const host=$("#recentProjects");
  const names=[currentProject,"SiteBoss","ForgeBoss"].filter(Boolean);
  host.innerHTML=[...new Set(names)].slice(0,3).map(n=>`<div class="recent" data-name="${n}"><b>${n}</b><small>Open project memory and Bible</small></div>`).join("");
  host.querySelectorAll(".recent").forEach(r=>r.onclick=()=>{setProject(r.dataset.name);showPage("chat")});
}
renderRecents();

$("#sparkBtn").onclick=()=>{
  if(!$("#ideaInput").value.trim()){alert("Describe the project idea first.");return}
  $("#questionModal").hidden=false;
};
$("#cancelQuestionsBtn").onclick=()=>$("#questionModal").hidden=true;
$("#forgeBibleBtn").onclick=()=>{
  const idea=$("#ideaInput").value.trim();
  const name=(idea.match(/\b(?:app|platform|system|tool|service)\s+(?:called\s+)?([A-Za-z0-9_-]+)/i)||[])[1] || "New Forge Project";
  setProject(name);
  const foundation={
    idea,
    who:$("#qWho").value.trim(),
    outcome:$("#qOutcome").value.trim(),
    limits:$("#qLimits").value.trim(),
    created:new Date().toISOString()
  };
  localStorage.setItem("fb_bible_demo",JSON.stringify(foundation));
  chats.push({role:"bot",text:"I have enough to forge the first Project Bible foundation. I will treat it as the project authority and only stop again for decisions that materially change the product.",time:new Date().toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})});
  saveChats();
  $("#questionModal").hidden=true;
  showPage("bible");
};

$("#chooseFolderBtn").onclick=()=>$("#folderPicker").click();
$("#folderPicker").onchange=()=>{
  const f=$("#folderPicker").files[0]; if(!f)return;
  const root=(f.webkitRelativePath||f.name).split("/")[0];
  $("#folderDisplay").textContent=root; setProject(root);
};
$("#loadLocalBtn").onclick=()=>{ if(currentProject) showPage("forge"); else alert("Load a folder first."); };

function detectProvider(url){
  if(/github\.com/i.test(url)) return "GitHub";
  if(/gitlab/i.test(url)) return "GitLab";
  if(/bitbucket/i.test(url)) return "Bitbucket";
  if(/dev\.azure\.com|visualstudio\.com/i.test(url)) return "Azure DevOps";
  return url ? "Generic Git" : "not detected";
}
$("#detectRepoBtn").onclick=()=>{
  $("#providerStatus").textContent="Provider: "+detectProvider($("#repoInput").value.trim());
};
$("#loadRepoBtn").onclick=()=>{
  const u=$("#repoInput").value.trim(); if(!u){alert("Paste a repository link first.");return}
  const parts=u.replace(/\.git$/,"").replace(/\/$/,"").split("/");
  setProject(parts[parts.length-1]||"Remote project");
  showPage("vault");
};

function saveChats(){localStorage.setItem("fb_chats",JSON.stringify(chats));renderChats()}
function renderChats(){
  const host=$("#chatStream");
  if(!chats.length){
    chats=[{role:"bot",text:"Forge Chat is project-aware. Tell me ideas, decisions, changes or questions. Important decisions can be promoted into the Bible; casual discussion stays in memory.",time:""}];
  }
  host.innerHTML=chats.map(c=>`<div class="bubble ${c.role}">${escapeHtml(c.text)}<small>${c.time||""}</small></div>`).join("");
  host.scrollTop=host.scrollHeight;
}
function escapeHtml(s){return s.replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
renderChats();
$("#sendChatBtn").onclick=()=>{
  const t=$("#chatInput").value.trim(); if(!t)return;
  const time=new Date().toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"});
  chats.push({role:"user",text:t,time});
  chats.push({role:"bot",text:"Saved to this project's conversation memory. If that changes an authoritative requirement, ForgeBoss would flag it for Bible promotion rather than silently rewriting the project.",time});
  $("#chatInput").value=""; saveChats();
};

function renderLogs(){
  $("#forgeLog").innerHTML=logs.map(([t,m])=>`<div class="event"><span class="time">${t}</span><span class="${m.startsWith("✓")?"ok":""}">${m}</span></div>`).join("");
}
renderLogs();

$("#quenchBtn").onclick=()=>{
  $("#forgeState").textContent="● QUENCHED";
  $("#forgeState").style.color="var(--warn)";
  $("#forgeNow").textContent="Safe stop requested. ForgeBoss is preserving evidence and project state.";
  const time=new Date().toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"});
  logs.unshift([time,"● Safe quench requested"]);
  renderLogs();
};

const modeText={
  "Auto Forge":"<b>Auto Forge:</b> start with Repair Rat / the cheapest suitable path and raise heat only when the evidence says it is needed. Never exceed the fuel cap.",
  "Repair Rat":"<b>Repair Rat:</b> local/proven repair path only. No paid escalation.",
  "Low Heat":"<b>Low Heat:</b> cheapest safe route with minimal paid escalation.",
  "Working Heat":"<b>Working Heat:</b> balance cost and capability.",
  "High Heat":"<b>High Heat:</b> move to stronger reasoning/models sooner.",
  "Full Forge":"<b>Full Forge:</b> allow the strongest approved model when justified, still bounded by the fuel cap and safety gates."
};
$("#modeSel").onchange=()=>$("#modeExplain").innerHTML=modeText[$("#modeSel").value];

let pendingProvider="";
$$(".connect-btn").forEach(b=>b.onclick=()=>{
  pendingProvider=b.dataset.provider;
  $("#secretLabel").textContent=pendingProvider.toUpperCase()+" CONNECTION";
  $("#secretInput").placeholder=pendingProvider==="GitHub" ? "Prefer OAuth / GitHub App. Token fallback only." : "Paste API key once";
  $("#secretEntry").hidden=false;
  $("#secretInput").focus();
});
$("#saveSecretBtn").onclick=()=>{
  const raw=$("#secretInput").value.trim();
  if(!raw){alert("Enter a key/token for this prototype connection test.");return}
  const last4=raw.slice(-4);
  const id=pendingProvider.toLowerCase().replace(/\s+/g,"");
  const status=document.getElementById(id+"Status");
  if(status){status.textContent="Connected ••••"+last4;status.classList.add("good")}
  // Deliberately DO NOT persist raw secret in this prototype.
  $("#secretInput").value="";
  $("#secretEntry").hidden=true;
  alert("Prototype connection sealed. Raw secret was not persisted. Production ForgeBoss must use OS-protected secret storage or OAuth.");
};

$("#saveSettingsBtn").onclick=()=>{
  const settings={
    mode:$("#defaultMode").value,
    cap:$("#defaultCap").value,
    duration:$("#defaultDuration").value,
    remember:$("#rememberChats").checked,
    promote:$("#promoteDecisions").checked
  };
  localStorage.setItem("fb_settings_demo",JSON.stringify(settings));
  alert("Forge defaults saved for this prototype.");
};

const savedSettings=JSON.parse(localStorage.getItem("fb_settings_demo")||"null");
if(savedSettings){
  $("#defaultMode").value=savedSettings.mode;
  $("#defaultCap").value=savedSettings.cap;
  $("#defaultDuration").value=savedSettings.duration;
  $("#rememberChats").checked=savedSettings.remember;
  $("#promoteDecisions").checked=savedSettings.promote;
}
